<a href="https://colab.research.google.com/github/soufianeodf/ML-Quora-Insincere-Questions-Classification/blob/main/quora.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Quora Insincere Questions Classification**

using Deep learning and NLP

In [1]:
import numpy as np
import pandas as pd
%matplotlib inline

train_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/quora competition/train.csv')
train_df.head()

qid  ... target
0  00002165364db923c7e6  ...      0
1  000032939017120e6e44  ...      0
2  0000412ca6e4628ce2cf  ...      0
3  000042bf85aa498cd78e  ...      0
4  0000455dfa3e01eae3af  ...      0

[5 rows x 3 columns]

### Tokenize and Clean Text

In [2]:
import spacy
nlp = spacy.load('en',disable=['parser', 'tagger','ner'])

nlp.max_length = 16981599

In [3]:
puncts = [',', '.', '"', ':', ')', '(', '-', '!', '?', '|', ';', 
          "'",  '&', '/', '[', ']', '>', '<', '%', '=', '#', '+', 
          '\\',  '§', '″', '′','¿','═', '$', '^', '*', '@', '^', '_', 
          '`', '{', '}', '~']

## Stemming

In [4]:
import nltk
# from nltk.stem.porter import PorterStemmer
from nltk.stem.snowball import SnowballStemmer

In [5]:
# p_stemmer = PorterStemmer()
s_stemmer = SnowballStemmer(language='english')

## Stop words

In [6]:
stop_words = nlp.Defaults.stop_words

print(nlp.Defaults.stop_words)
print(len(nlp.Defaults.stop_words))

{'by', 'down', 'hers', 'behind', 'latterly', '’ve', 'thereby', 'very', 'beforehand', 'ever', 'you', 'wherein', 'the', 'many', 'also', 'seems', 'them', 'in', 'between', 'often', 'almost', 'thence', 'towards', 'nowhere', 'beyond', 'if', 'may', 'really', 'who', 'under', 'hereby', 'hereafter', 'these', '‘m', 'others', 'forty', 'he', 'alone', 'throughout', 'they', 'his', 'toward', 'although', 'amongst', 'anyway', 'their', 'had', 'much', 'only', 'therein', 'less', 'a', 'someone', 'nine', 'next', 'then', 'seem', 'without', 'noone', 'and', 'already', 'itself', 'did', 'except', 'perhaps', 'empty', 'out', '‘ve', "'ve", 'us', "'re", 'sometime', 'each', 'five', 'just', 'might', 'ourselves', 'never', 'hereupon', 'into', 'should', 'thereupon', 'this', 'myself', '‘d', 'rather', 'everywhere', 'after', 'six', 'back', 'before', 'are', 'whereby', 'anyone', 'elsewhere', 'seemed', 'about', 'become', 'becoming', 'moreover', 'herein', 'four', 'hence', 'say', 'was', 'onto', 'ca', 'latter', 'please', 'amount',

### Spliting data

In [7]:
X = train_df['question_text'][:653061]
y = train_df['target'][:653061]

text_sequences = [[s_stemmer.stem(token.text.lower()) for token in nlp(phrase) if token.text not in puncts and token.text not in stop_words] for phrase in X]

In [8]:
text_sequences[0]

['how', 'quebec', 'nationalist', 'provinc', 'nation', '1960s']

In [9]:
index_of_max = text_sequences.index(max(text_sequences))
len_of_max = len(text_sequences[index_of_max])
print(len_of_max)

27


# KerasX

### Keras Tokenization

In [10]:
from keras.preprocessing.text import Tokenizer

In [11]:
# integer encode sequences of words
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)
sequences = tokenizer.texts_to_sequences(text_sequences)

In [12]:
# sequences
sequences[index_of_max]

[46354,
 46354,
 1203,
 3623,
 5196,
 404,
 75,
 1175,
 438,
 188,
 13,
 42599,
 368,
 396,
 233,
 22638,
 177,
 85305,
 4913,
 1369,
 323,
 7050,
 832,
 2926,
 605,
 3623,
 5196]

## Padding

In [13]:
from keras.preprocessing.sequence import pad_sequences

sequences_bis = pad_sequences(sequences, maxlen=len_of_max, truncating='pre')

In [14]:
sequences_bis[index_of_max]

array([46354, 46354,  1203,  3623,  5196,   404,    75,  1175,   438,
         188,    13, 42599,   368,   396,   233, 22638,   177, 85305,
        4913,  1369,   323,  7050,   832,  2926,   605,  3623,  5196],
      dtype=int32)

In [15]:
tokenizer.index_word

{1: 'what',
 2: 'i',
 3: 'how',
 4: 'whi',
 5: 'is',
 6: 'best',
 7: 'peopl',
 8: 'like',
 9: 'can',
 10: 'which',
 11: 'do',
 12: 'good',
 13: 'if',
 14: 'india',
 15: 'are',
 16: 'year',
 17: 'think',
 18: 'differ',
 19: 'time',
 20: 'way',
 21: 'work',
 22: 'use',
 23: 'want',
 24: 'doe',
 25: 'person',
 26: 'who',
 27: 'know',
 28: 'life',
 29: 'feel',
 30: 'countri',
 31: 'start',
 32: 'where',
 33: 'thing',
 34: 'mean',
 35: 'happen',
 36: 'find',
 37: 'job',
 38: 'learn',
 39: 'engin',
 40: 'indian',
 41: 'world',
 42: 'book',
 43: 'should',
 44: 'need',
 45: 'have',
 46: 'student',
 47: 'live',
 48: 'better',
 49: 'day',
 50: 'quora',
 51: 'possibl',
 52: 'will',
 53: 'girl',
 54: 'univers',
 55: 'trump',
 56: 'compani',
 57: 'when',
 58: 'new',
 59: 'school',
 60: 'studi',
 61: 'chang',
 62: 'colleg',
 63: 'love',
 64: 'friend',
 65: 'women',
 66: 'state',
 67: 'help',
 68: 'american',
 69: 'question',
 70: 'look',
 71: 'us',
 72: 'busi',
 73: 'money',
 74: 'develop',
 75: 'lo

In [16]:
tokenizer.word_counts

OrderedDict([('how', 131609),
             ('quebec', 83),
             ('nationalist', 169),
             ('provinc', 137),
             ('nation', 3023),
             ('1960s', 59),
             ('do', 20551),
             ('adopt', 600),
             ('dog', 2776),
             ('encourag', 316),
             ('peopl', 28580),
             ('shop', 903),
             ('whi', 72687),
             ('veloc', 424),
             ('affect', 3159),
             ('time', 14128),
             ('doe', 11711),
             ('space', 1961),
             ('geometri', 112),
             ('otto', 29),
             ('von', 60),
             ('guerick', 1),
             ('magdeburg', 3),
             ('hemispher', 56),
             ('can', 26405),
             ('i', 164579),
             ('convert', 1230),
             ('montra', 4),
             ('helicon', 1),
             ('d', 603),
             ('mountain', 376),
             ('bike', 672),
             ('chang', 7055),
             ('tyre', 95

In [17]:
vocabulary_size = len(tokenizer.word_counts)
vocabulary_size

117564

### Convert to Numpy Matrix

In [18]:
import numpy as np

In [19]:
sequences_bis = np.array(sequences_bis)

In [20]:
sequences_bis

array([[   0,    0,    0, ..., 3783,  212, 6296],
       [   0,    0,    0, ...,    7, 1344,  929],
       [   0,    0,    0, ...,  196,  381, 4319],
       ...,
       [   0,    0,    0, ...,  561, 4005,  926],
       [   0,    0,    0, ...,  708,  232,    7],
       [   0,    0,    0, ...,    8,  762,  212]], dtype=int32)

In [21]:
seq_len = sequences_bis.shape[1]

In [22]:
### splitting dataset in to train_set and test_set
from sklearn.model_selection import train_test_split

x_train,x_val,y_train,y_val = train_test_split(sequences_bis, y, test_size=0.2, stratify=y, random_state=42)

# Creating an LSTM based model

In [23]:
import keras
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding

In [24]:
def create_model(vocabulary_size, seq_len):
    model = Sequential()
    model.add(Embedding(vocabulary_size, seq_len, input_length=seq_len))
    model.add(LSTM(seq_len*2, return_sequences=True))
    model.add(LSTM(seq_len*2))
    model.add(Dense(150*3, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
   
    model.summary()
    
    return model

In [25]:
model = create_model(vocabulary_size + 1, seq_len)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 27, 27)            3174255   
_________________________________________________________________
lstm (LSTM)                  (None, 27, 54)            17712     
_________________________________________________________________
lstm_1 (LSTM)                (None, 54)                23544     
_________________________________________________________________
dense (Dense)                (None, 450)               24750     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 451       
Total params: 3,240,712
Trainable params: 3,240,712
Non-trainable params: 0
_________________________________________________________________


In [26]:
from pickle import dump,load

## Fit (Train) the Model

In [28]:
model.fit(sequences_bis, y, batch_size=128, epochs=5, verbose=2)

# es = callbacks.EarlyStopping(patience=5)

# model.fit(x_train, y_train, epochs=5, validation_data=(x_val,y_val),batch_size=128, verbose=2,callbacks=[es])

Epoch 1/5
5103/5103 - 476s - loss: 0.0000e+00 - accuracy: 0.9384
Epoch 2/5
5103/5103 - 482s - loss: 0.0000e+00 - accuracy: 0.9386
Epoch 3/5
5103/5103 - 483s - loss: 0.0000e+00 - accuracy: 0.9386
Epoch 4/5
5103/5103 - 489s - loss: 0.0000e+00 - accuracy: 0.9386
Epoch 5/5
5103/5103 - 491s - loss: 0.0000e+00 - accuracy: 0.9386


# Evaluating Model Performance

In [30]:
model.metrics_names 

['loss', 'accuracy']

In [31]:
model.evaluate(x_val,y_val)

4082/4082 [==============================] - 35s 8ms/step - loss: 0.0000e+00 - accuracy: 0.9386


[0.0, 0.9385513067245483]

In [33]:
from sklearn.metrics import confusion_matrix,classification_report

In [34]:
predictions = model.predict_classes(x_val)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [35]:
predictions

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

In [36]:
confusion_matrix(y_val,predictions)

array([[122587,      0],
       [  8026,      0]])

In [37]:
print(classification_report(y_val,predictions))

              precision    recall  f1-score   support

           0       0.94      1.00      0.97    122587
           1       0.00      0.00      0.00      8026

    accuracy                           0.94    130613
   macro avg       0.47      0.50      0.48    130613
weighted avg       0.88      0.94      0.91    130613



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Saving and Loading Models

In [ ]:
model.save('myfirstmodel.h5')

In [ ]:
from keras.models import load_model

In [ ]:
newmodel = load_model('myfirstmodel.h5')

In [ ]:
newmodel.predict_classes(x_train)